name: PlatformIO Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Fetch Library Dependencies
        run: pio pkg install

      - name: Create Mock arduino_secrets.h File
        run: echo -e "#define DEFALT_SECRET_SSID \"MOCK_SSID\"\n#define DEFAULT_SECRET_PASS \"MOCK_PASS\"\n#define DEFAULT_SERVER_ADDR \"127.0.0.1:1234\"\n" > include/arduino_secrets.h

      - name: Copy Fonts to GFX Library include directory
        run: cp Fonts/* ".pio/libdeps/uno_r4_wifi/Adafruit GFX Library/Fonts"

      - name: Build PlatformIO Project
        run: pio run
